name: Build all with CMake

on: [push]

env:
  HOME_PATH: ${{ github.workspace }}
  SOURCE_PATH: src/c/main
  TEST_PATH: src/c/test
  BUILD_PATH: build
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    #- name: Install CLib package manager
    #  shell: bash
    #  run: |
    #    echo ">>> Install libcurl"
    #    sudo apt-get install libcurl4-gnutls-dev -qq

    #    echo ">>> Download, build and install clib"
    #    git clone https://github.com/clibs/clib.git /tmp/clib
    #    cd /tmp/clib
    #    make
    #    sudo make install

    #- name: Install CMocka library
    #  shell: bash
    #  run: |
    #    clib install cmocka

    - name: Install splint code validation tool
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install splint

    - name: Install CMocka library
      shell: bash
      run: |
        sudo apt-get install libcmocka-dev

    - name: Create build environment
      shell: bash
      run: |
        cmake -E make_directory ${HOME_PATH}/${BUILD_PATH}

    - name: Build makefiles from CMake files
      shell: bash
      run: |
        cd ${HOME_PATH}/${BUILD_PATH}
        cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${HOME_PATH}

    - name: Validate all source code with splint
      shell: bash
      run: |
        cd ${HOME_PATH}/${SOURCE_PATH}
        echo ">>>>> Validating all source code with splint"
        cd ${HOME_PATH}/${TEST_PATH}
        echo ">>>>> Validating all test code with splint"

    - name: Build target from source code
      shell: bash
      run: |
        cd ${HOME_PATH}/${BUILD_PATH}
        cmake --build .
    #    cmake -DSOURCE_DIRECTORY="${HOME_PATH}/${SOURCE_PATH}" -DTEST_DIRECTORY="${HOME_PATH}/${TEST_PATH}" --build . --config ${BUILD_TYPE}

    - name: Execute all unit tests using CTest
      shell: bash
      run: |
        cd ${HOME_PATH}/${BUILD_PATH}
        export CMOCKA_MESSAGE_OUTPUT=STDOUT
        ctest
    #  run: ctest -C $BUILD_TYPE
