name: Build all with CMake

on: [push]

env:
  HOME_PATH: ${{ github.workspace }}
  #SOURCE_PATH: ${HOME_PATH}/src/c/main
  SOURCE_PATH: src/c/main
  TEST_PATH: ${HOME_PATH}/src/c/test
  #BUILD_PATH: ${HOME_PATH}/build
  BUILD_PATH: ${{ SOURCE_PATH }}/build
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Show build directory
      shell: bash
    #  working-directory: $SOURCE_PATH
      run: |
        echo HOME_PATH: ${HOME_PATH}
        echo BUILD_PATH: ${BUILD_PATH}

    - name: Create build directory
      shell: bash
    #  working-directory: $SOURCE_PATH
      run: mkdir $BUILD_PATH

    - name: Build makefiles from CMake
      shell: bash
      run: cmake

    - name: Build target from source code
      shell: bash
      run: cmake --build $BUILD_PATH

    #- name: find for files
    #  shell: bash
    #  working-directory: $HOME_PATH
    #  run: find . -print

    #- name: Create Build Environment
    #  shell: bash
    #  working-directory: $BUILD_PATH
    #  run: cmake -E make_directory $BUILD_PATH

    #- name: Configure CMake
    #  shell: bash
    #  working-directory: $BUILD_PATH
    #  run: make cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    #- name: Build
    #  shell: bash
    #  working-directory: $BUILD_PATH
    #  run: cmake -DSOURCE_DIRECTORY=$SOURCE_PATH -DTEST_DIRECTORY=$TEST_PATH --build . --config $BUILD_TYPE

    #- name: Test
    #  working-directory: $BUILD_PATH
    #  shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C $BUILD_TYPE
