name: CMake

on: [push]

env:
  SOURCE_DIRECTORY: ${{ github.workspace }}/src/c/main
  TEST_DIRECTORY: ${{ github.workspace }}/src/c/test
  BUILD_DIRECTORY: ${{ github.workspace }}/build
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory $BUILD_DIRECTORY

    - name: Configure CMake
      shell: bash
      working-directory: $BUILD_DIRECTORY
      run: cmake $GITHUB_WORKSPACE -DSOURCE_DIRECTORY=$SOURCE_DIRECTORY -DTEST_DIRECTORY=$TEST_DIRECTORY -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: $BUILD_DIRECTORY
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: $BUILD_DIRECTORY
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
