name: Build all with CMake

on: [push]

env:
  HOME_PATH: ${{ github.workspace }}
  SOURCE_PATH: src/c/main
  TEST_PATH: src/c/test
  BUILD_PATH: src/c/main/build
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    #- name: Create build directory
    #  shell: bash
    #  run: mkdir $BUILD_PATH

    - name: Create build environment
      shell: bash
      run: |
        cd ${HOME_PATH}/${BUILD_PATH}
        cmake -E make_directory ${BUILD_PATH}

    - name: Build makefiles from CMake files
      shell: bash
      run: |
        cd ${HOME_PATH}/${BUILD_PATH}
        make cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

    - name: Build target from source code
      shell: bash
      run: |
        cd ${HOME_PATH}/${BUILD_PATH}
        cmake -DSOURCE_DIRECTORY=${SOURCE_PATH} -DTEST_DIRECTORY=${TEST_PATH} --build . --config ${BUILD_TYPE}

    #- name: Configure CMake
    #  shell: bash
    #  working-directory: $BUILD_PATH
    #  run: make cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    #- name: Build
    #  shell: bash
    #  working-directory: $BUILD_PATH
    #  run: cmake -DSOURCE_DIRECTORY=$SOURCE_PATH -DTEST_DIRECTORY=$TEST_PATH --build . --config $BUILD_TYPE

    #- name: Test
    #  working-directory: $BUILD_PATH
    #  shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C $BUILD_TYPE
